<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>nullable</WarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MetaFac.CG4.Schemas" Version="3.2.4" />
		<PackageReference Include="Nerdbank.GitVersioning" Version="3.7.115">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
