#region Notices
// <auto-generated>
// Warning: This file was automatically generated. Changes to this file may
// cause incorrect behavior and will be lost when this file is regenerated.
// </auto-generated>
// <information>
// This file was generated using MetaFac.CG4 tools and user supplied metadata.
// Generator: Contracts.2.9
// Metadata : MetaFac.Service.CG5.Schema
// </information>
#endregion
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS8019 // Unnecessary using directive
using MetaFac.CG4.Runtime;
using MetaFac.Memory;
using MetaFac.Mutability;
using System;
using System.Collections.Generic;
using System.Numerics;

namespace MetaFac.Service.CG5
{
    public partial interface IBaseMessage : IEntityBase
    {
        Guid RequestId { get; }
    }
    public partial interface IBaseRequest : IBaseMessage
    {
    }
    public partial interface IBaseResponse : IBaseMessage
    {
        Boolean Succeeded { get; }
        String? FailReason { get; }
        IReadOnlyList<ILogMessage?>? Messages { get; }
    }
    public partial interface ILogMessage : IEntityBase
    {
        Int32 Severity { get; }
        String? MessageTemplate { get; }
        IReadOnlyList<String?>? MessageParameters { get; }
    }
    public partial interface INameValuePair : IEntityBase
    {
        String? Name { get; }
        String? Value { get; }
    }
    public partial interface IGeneratorsInfo : IEntityBase
    {
        String? AssmVersion { get; }
        String? InfoVersion { get; }
        String? FileVersion { get; }
    }
    public partial interface IGetServerInfoRequest : IBaseRequest
    {
    }
    public partial interface IGetServerInfoResponse : IBaseResponse
    {
        IReadOnlyList<INameValuePair?>? ServerProperties { get; }
    }
    public partial interface IGetGeneratorsInfoRequest : IBaseRequest
    {
    }
    public partial interface IGetGeneratorsInfoResponse : IBaseResponse
    {
        IGeneratorsInfo? VersionInfo { get; }
    }
    public partial interface IGetTemplateNamesRequest : IBaseRequest
    {
    }
    public partial interface IGetTemplateNamesResponse : IBaseResponse
    {
        IReadOnlyList<String?>? TemplateNames { get; }
    }
    public partial interface IGetTemplateRequest : IBaseRequest
    {
        String? TemplateName { get; }
    }
    public partial interface IGetTemplateResponse : IBaseResponse
    {
        IReadOnlyList<String?>? Template { get; }
    }
}
