#region Notices
// <auto-generated>
// Warning: This file was automatically generated. Changes to this file may
// cause incorrect behavior and will be lost when this file is regenerated.
// </auto-generated>
// <information>
// This file was generated using MetaFac.CG4 tools and user supplied metadata.
// Generator: Contracts.2.9
// Metadata : MetaFac.Service.Accounts.Schema
// </information>
#endregion
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CS8019 // Unnecessary using directive
using MetaFac.CG4.Runtime;
using MetaFac.Memory;
using MetaFac.Mutability;
using System;
using System.Collections.Generic;
using System.Numerics;

namespace MetaFac.Service.Accounts
{
    public partial interface IBaseMessage : IEntityBase
    {
        Guid RequestId { get; }
    }
    public partial interface IBaseRequest : IBaseMessage
    {
    }
    public partial interface IBaseResponse : IBaseMessage
    {
        Boolean Succeeded { get; }
        String? FailReason { get; }
        IReadOnlyList<ILogMessage?>? Messages { get; }
    }
    public partial interface ILogMessage : IEntityBase
    {
        Int32 Severity { get; }
        String? MessageTemplate { get; }
        IReadOnlyList<String?>? MessageParameters { get; }
    }
    public partial interface INameValuePair : IEntityBase
    {
        String? Name { get; }
        String? Value { get; }
    }
    public partial interface IGetServerInfoRequest : IBaseRequest
    {
    }
    public partial interface IGetServerInfoResponse : IBaseResponse
    {
        IReadOnlyList<INameValuePair?>? ServerProperties { get; }
    }
    public partial interface IAccountRequest : IBaseRequest
    {
    }
    public partial interface IAccountResponse : IBaseResponse
    {
    }
    public partial interface IGetNewAccountIdRequest : IAccountRequest
    {
    }
    public partial interface IGetNewAccountIdResponse : IAccountResponse
    {
        String? CreateToken { get; }
    }
    public partial interface ICreateAccountRequest : IAccountRequest
    {
        String? CreateToken { get; }
        String? ShortName { get; }
        String? PrimaryEmailAddress { get; }
        String? BackupEmailAddress { get; }
    }
    public partial interface ICreateAccountResponse : IAccountResponse
    {
        String? VerifyToken { get; }
    }
    public partial interface IVerifyAccountRequest : IAccountRequest
    {
        String? VerifyToken { get; }
        String? PrimaryEmailVerifyCode { get; }
        String? BackupEmailVerifyCode { get; }
    }
    public partial interface IVerifyAccountResponse : IAccountResponse
    {
        String? AccessToken { get; }
    }
    public partial interface IModifyAccountRequest : IAccountRequest
    {
        String? AccessToken { get; }
        String? ShortName { get; }
        String? PrimaryEmailAddress { get; }
        String? BackupEmailAddress { get; }
    }
    public partial interface IModifyAccountResponse : IAccountResponse
    {
        String? VerifyToken { get; }
    }
    public partial interface IGetSecretRequest : IAccountRequest
    {
        String? LicenseCode { get; }
        Guid SecretGuid { get; }
    }
    public partial interface IGetSecretResponse : IAccountResponse
    {
        Guid SecretGuid { get; }
        String? SecretText { get; }
    }
    public partial interface IGetAdminTokenRequest : IAccountRequest
    {
        String? AccessToken { get; }
        String? MasterToken { get; }
    }
    public partial interface IGetAdminTokenResponse : IAccountResponse
    {
        String? AdminToken { get; }
    }
    public partial interface IAddSecretRequest : IAccountRequest
    {
        String? AdminToken { get; }
        Guid SecretGuid { get; }
        String? SecretText { get; }
    }
    public partial interface IAddSecretResponse : IAccountResponse
    {
    }
    public partial interface ICommencePurchaseRequest : IAccountRequest
    {
        String? AccessToken { get; }
        ICreditCardDetails? CreditCard { get; }
        String? LicenseTier { get; }
    }
    public partial interface ICommencePurchaseResponse : IAccountResponse
    {
    }
    public partial interface ICompletePurchaseRequest : IAccountRequest
    {
        String? AccessToken { get; }
        String? VerifyCode { get; }
    }
    public partial interface ICompletePurchaseResponse : IAccountResponse
    {
        String? LicenseCode { get; }
    }
    public partial interface ICreditCardDetails : IEntityBase
    {
        String? Number { get; }
        UInt16 ExpiryYear { get; }
        Byte ExpiryMonth { get; }
        String? CVC { get; }
    }
}
